workflows:
  build-apk:
    name: Build Debug APK (no signing)
    environment:
      flutter: "3.16.9"
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
